# Generated by Django 4.2.7 on 2023-12-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('cno', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='dish',
            fields=[
                ('dno', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='dish_chef',
            fields=[
                ('df_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dno', models.IntegerField()),
                ('cno', models.IntegerField()),
                ('Datetime', models.DateField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
