# Generated by Django 4.2.7 on 2023-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_chef',
            name='Datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
