# Generated by Django 4.2.7 on 2023-12-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eat_in',
            fields=[
                ('Datetime', models.DateField()),
                ('eat_in_no', models.IntegerField(primary_key=True, serialize=False)),
                ('tno', models.IntegerField()),
                ('dno', models.IntegerField()),
                ('comments', models.CharField(max_length=128)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='take_away',
            fields=[
                ('Datetime', models.DateField()),
                ('take_away_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dno', models.IntegerField()),
                ('comments', models.CharField(max_length=128)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
