# Generated by Django 4.2.7 on 2023-12-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat_in',
            name='Datetime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='take_away',
            name='Datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
