# Generated by Django 4.2.7 on 2023-12-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_eat_in_eat_in_no_alter_take_away_take_away_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat_in',
            name='eat_in_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='take_away',
            name='take_away_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
